---
title: "data-visualization"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(leaflet)
library(dplyr)
library(tidyr)
library(ggplot2)
library(DT)
library(scales) # install.packages("scales")
```


Load data from KNB repo:

```{r}
data_url <- "https://knb.ecoinformatics.org/knb/d1/mn/v2/object/urn%3Auuid%3Af119a05b-bbe7-4aea-93c6-85434dcb1c5e"

esc <- tryCatch(
    read.csv("data/escapement.csv", stringsAsFactors = FALSE),
    error=function(cond) {
        message(paste("Escapement file does not seem to exist, so get it from the KNB."))
        esc <- read.csv(url(data_url, method = "libcurl"), stringsAsFactors = FALSE)
        return(esc)
    }
)

head(esc)
```


```{r}
summary(esc)
```

```{r}
annual_esc <- esc %>%
    mutate(Year = lubridate::year(sampleDate), #also 'separate' by -
           Month = lubridate::month(sampleDate),
           Day = lubridate::day(sampleDate)) %>%
    group_by(Year, SASAP.Region, Species) %>% 
    summarise(escapement = sum(DailyCount))

annual_esc <- annual_esc %>% 
      filter(Species %in% c("Chinook", "Sockeye", "Chum", "Coho", "Pink")) #select only salmonid species
```


```{r}
ggplot(annual_esc, aes(x = Species, y = escapement)) +
  geom_col()
```


```{r}
ggplot(annual_esc, aes(x = Species, y = escapement, fill = "blue")) +
  geom_col()
```


```{r}
ggplot(annual_esc, aes(x = Species, y = escapement)) +
  geom_col(fill = "blue")
```


```{r}
ggplot(annual_esc, aes(x = Species, y = escapement, fill = SASAP.Region)) +
  geom_col()
```


```{r}
annual_esc %>% 
  filter(SASAP.Region == "Kodiak") %>% 
ggplot(aes(x = Year, y = escapement, color = Species)) + 
    geom_line() +
    geom_point()
```


```{r}
kodiak_esc <- annual_esc %>% 
  filter(SASAP.Region == "Kodiak")
```


```{r}
ggplot(kodiak_esc, aes(x = Year, y = escapement, color = Species)) + 
    geom_line() +
    geom_point() +
    ylab("Escapement") +
    ggtitle("Kodiak Salmon Escapement") +
    theme_bw()
```


#9.2.4

```{r}
locations <- esc %>% 
  distinct(Location, Latitude, Longitude) %>% 
  drop_na()
```

```{r}
datatable(locations)
```


```{r}
leaflet(locations) %>% 
  addTiles() %>% 
  addMarkers(lng = ~Longitude, lat = ~Latitude, popup = ~ Location)
```



```{r}
leaflet(locations) %>% 
  addWMSTiles("https://www.gebco.net/data_and_products/gebco_web_services/web_map_service/mapserv?",
              layers = 'GEBCO_LATEST',
              attribution = "Imagery reproduced from the GEBCO_2014 Grid, version 20150318, www.gebco.net") %>%
  addCircleMarkers(lng = ~Longitude,
                   lat = ~Latitude,
                   popup = ~ Location,
                   radius = 5,
                   # set fill properties
                   fillColor = "salmon",
                   fillOpacity = 1,
                   # set stroke properties
                   stroke = T,
                   weight = 0.5,
                   color = "white",
                   opacity = 1)
```



